### ISSUE TITLE
adaptivelassoCoefficients example gives error

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2extra#15]
When running the following code, I get the error below.

```r

one.cmt <- function() {
  ini({
    ## You may label each parameter with a comment
    tka <- 0.45 # Log Ka
    tcl <- log(c(0, 2.7, 100)) # Log Cl
    ## This works with interactive models
    ## You may also label the preceding line with label("label text")
    tv <- 3.45; label("log V")
    ## the label("Label name") works with all models
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    linCmt() ~ add(add.sd)
  })
}

d <- nlmixr2data::theo_sd
d$SEX <-0
d$SEX[d$ID<=6] <-1

fit <- nlmixr2(one.cmt, d, est = "focei", control = nlmixr2est::foceiControl(print = 0))
varsVec <- c("ka","cl","v")
covarsVec <- c("WT")
catvarsVec <- c("SEX")

# Adaptive Lasso coefficients:

lassoDf <- adaptivelassoCoefficients(fit, varsVec, covarsVec, catvarsVec)
```

```
✔ Training and Testing data sets successfully created for cross-validation for fold number 1
Error : missing 'SEX_0' in data
[1] "error fitting the model for the training dataset "
<simpleError: missing 'SEX_0' in data>
Error : missing 'SEX_0' in data
[1] "error fitting the model for the testing dataset "
<simpleError: missing 'SEX_0' in data>
✖ the 'fit' object needs to have an objective functions value associated with it
ℹ try computing 'fit$objDf$$`Log-likelihood`' in console to compute and store the corresponding OBJF value
Error: aborting...objf value not associated with the current 'fit' object
```

**Comment by mattfidler** [comment]
@vsarsani if you have time can you look at this?

**Comment by billdenney** [comment]
@vsarsani , I made it past the original issue, but now there are issues running the horseshoe examples.  Can you help with this?

What I've done so far is in #16

```r
one.cmt <- function() {
  ini({
    ## You may label each parameter with a comment
    tka <- 0.45 # Log Ka
    tcl <- log(c(0, 2.7, 100)) # Log Cl
    ## This works with interactive models
    ## You may also label the preceding line with label("label text")
    tv <- 3.45; label("log V")
    ## the label("Label name") works with all models
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    linCmt() ~ add(add.sd)
  })
}

d <- nlmixr2data::theo_sd
fit <- nlmixr2(one.cmt, d, "focei", control=nlmixr2est::foceiControl(print=0))
covarsVec <- "WT"

hsDf <- horseshoeSummardf(fit, covarsVec)
# Error in horseshoe(df = 1, scale_global = tau0, df_global = 1) :
#  object 'tau0' not found
```

**Comment by vsarsani** [comment]
Working on this.

**Comment by billdenney** [comment]
@vsarsani , in case it helps, here is the location of the issue: https://github.com/nlmixr2/nlmixr2extra/runs/8173306498?check_suite_focus=true#step:20:208 (It's the same as what I noted above.)

When making the PR, can you build on top of #16 ?  There are numerous changes there to make the other examples run and whitespace changes.  It would be simplest to have it all in one place.

**Comment by vsarsani** [comment]
@mattfidler @billdenney 
1) I have resolved horseshoe issues ( a) usage of brms::horseshoe or brms::lasso inside prior throws errors. So created empty function     b) tau0 issue is now resolved  )



2) For all lasso or even regular models,nlmixr2 fit seems to fail causing issues. This wasn't the case before.  Will you able to look into why rxode compilation is failing?  

Very simple example 

one.cmt<-function(){
ini({
##Youmaylabeleachparameterwithacomment
tka<-0.45#LogKa
tcl<-log(c(0,2.7,100))#LogCl
##Thisworkswithinteractivemodels
##Youmayalsolabeltheprecedinglinewithlabel("labeltext")
tv<-3.45;label("logV")
##thelabel("Labelname")workswithallmodels
eta.ka~0.6
eta.cl~0.3
eta.v~0.1
add.sd<-0.7
})
model({
ka<-exp(tka+eta.ka)
cl<-exp(tcl+eta.cl)
v<-exp(tv+eta.v)
linCmt()~add(add.sd)
})
}

d<-nlmixr2data::theo_sd
mod <- buildupatedUI(ui,varsVec,covarsVec="WT")
fit<-nlmixr2(mod,d,"focei")



Last few lines of error
//Initialize the dll to match rxode2's calls
void R_init_rx_a1264d0a7743aaad8c85da22a1c3df78_x64(DllInfo *info){
  // Get C callables on load; Otherwise it isn't thread safe
  R_init0_rx_a1264d0a7743aaad8c85da22a1c3df78_x64();
  static const R_CallMethodDef callMethods[]  = {
    {"rx_a1264d0a7743aaad8c85da22a1c3df78_x64_model_vars", (DL_FUNC) &rx_a1264d0a7743aaad8c85da22a1c3df78_x64_model_vars, 0},
    {NULL, NULL, 0}
  };

  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info,FALSE);
  _assignFuns0();

}

void R_unload_rx_a1264d0a7743aaad8c85da22a1c3df78_x64 (DllInfo *info){
  // Free resources required for single subject solve.
  SEXP _mv = PROTECT(_rxGetModelLib("rx_a1264d0a7743aaad8c85da22a1c3df78_x64_model_vars"));
  if (!isNull(_mv)){
    _rxRmModelLib("rx_a1264d0a7743aaad8c85da22a1c3df78_x64_model_vars");
  }
  UNPROTECT(1);
}
Error : error building model
Error: error building model
